import {
    Github,
    Twitter,
    Linkedin,
    Mail,
    Globe,
    ExternalLink,
    Code2,
    Cpu,
    BookOpen,
    Layers,
    User,
    Home,
    Briefcase,
    Menu,
    X,
    ArrowRight,
    Terminal,
    GitBranch,
    Star,
    Coffee
} from "lucide-react";

export const Icons = {
    github: Github,
    twitter: Twitter,
    linkedin: Linkedin,
    mail: Mail,
    globe: Globe,
    external: ExternalLink,
    code: Code2,
    cpu: Cpu,
    blog: BookOpen,
    stack: Layers,
    user: User,
    home: Home,
    works: Briefcase,
    menu: Menu,
    close: X,
    arrowRight: ArrowRight,
    terminal: Terminal,
    git: GitBranch,
    star: Star,
    coffee: Coffee
};
